services:
  bot:
    build:
      context: .
      dockerfile: ./CrTelegramBot/Dockerfile
    container_name: crtelegrambot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      BotConfig__ClashRoyaleApiToken: ${CLASH_TOKEN}
      BotConfig__TelegramBotToken: ${TELEGRAM_TOKEN}
    networks:
      - infra_net

networks:
  infra_net:
    external: true